### ISSUE TITLE
The ruby install did not use the latest version.

### ISSUE THREAD

**Issue by norman-abramovitz** [starkandwayne/jumpbox#16]
I got the following warning when using the jumpbox script.   

> ruby-2.2.4 - #adjusting #shebangs for (gem irb erb ri rdoc testrb rake).
> Install of ruby-2.2.4 - #complete
> **Please be aware that you just installed a ruby that requires 1 patches just to be compiled on an up to date linux system.**
> **This may have known and unaccounted for security vulnerabilities.**
> **Please consider upgrading to ruby-2.3.0 which will have all of the latest security patches.**
> Ruby was built without documentation, to build it run: rvm docs generate-ri
>    installed  (ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-linux])

Should the jumpbox script build and install the latest stable version automatically?

**Comment by jhunt** [comment]
We may want to look at a newer version of Ruby, but latest stable may not play nicely with all BOSH CLIs

**Comment by norman-abramovitz** [comment]
Ok,  FYI The latest version of cf ships with ruby 2.3.  as well as 2.1.8.
