### ISSUE TITLE
Seems like the cf command is installed every time instead of knowing it was installed already

### ISSUE THREAD

**Issue by norman-abramovitz** [starkandwayne/jumpbox#17]
The cf command seems to be installed each time you run "jumpbox user" command instead of figuring out it was installed already. 

The custom image did have the latest jumpbox release v49.

> 23 gems installed
>    installed BOSH CLI (BOSH 1.3184.1.0)
> **>> Installing cf**
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
>   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
> 100 6389k  100 6389k    0     0  3733k      0  0:00:01  0:00:01 --:--:-- 8129k
>  **installed CF CLI (cf version 6.21.1+6fd3c9f-2016-08-10)**
> Your Full Name (for git): Norman Abramovitz
> Your Email Address (for git): norm@starkandwayne.com
>    git is configured
> 
> 
> 
>    ALL DONE
> Norman@bastion:~$ exit
> logout
> Connection to 104.198.142.25 closed.
> Normans-MacBook-Pro:codex-google Norman$ gcloud compute ssh bastion --zone us-central1-a
> Welcome to Ubuntu 16.04.1 LTS (GNU/Linux 4.4.0-36-generic x86_64)
> 
>  * Documentation:  https://help.ubuntu.com
>  * Management:     https://landscape.canonical.com
>  * Support:        https://ubuntu.com/advantage
> 
>   Get cloud support with Ubuntu Advantage Cloud Guest:
>     http://www.ubuntu.com/business/services/cloud
> 
> 0 packages can be updated.
> 0 updates are security updates.
> 
> 
> Last login: Tue Sep 13 14:25:04 2016 from 99.90.69.58
> Norman@bastion:~$ jumpbox user
> 
> >> Installing rvm
>    RVM is already installed (rvm 1.27.0 (latest) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/])
> >> Checking for ruby v2.2.4
>    ruby is already installed (ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-linux])
> >> Checking for bosh v1.3184.1.0
>    bosh is already installed (BOSH 1.3184.1.0)
> **>> Installing cf**
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
>   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
> 100 6389k  100 6389k    0     0  2305k      0  0:00:02  0:00:02 --:--:-- 4388k
>    

> **installed CF CLI (cf version 6.21.1+6fd3c9f-2016-08-10)**

>    Git username is already set to 'Norman Abramovitz'
>    Git email address is already set to 'norm@starkandwayne.com'
>    git is configured
> 
> 
> 
>    ALL DONE

> Norman@bastion:~$ exit
> logout
> Connection to 104.198.142.25 closed.
> Normans-MacBook-Pro:codex-google Norman$ gcloud compute ssh bastion --zone us-central1-a
> Welcome to Ubuntu 16.04.1 LTS (GNU/Linux 4.4.0-36-generic x86_64)
> 
>  * Documentation:  https://help.ubuntu.com
>  * Management:     https://landscape.canonical.com
>  * Support:        https://ubuntu.com/advantage
> 
>   Get cloud support with Ubuntu Advantage Cloud Guest:
>     http://www.ubuntu.com/business/services/cloud
> 
> 0 packages can be updated.
> 0 updates are security updates.
> 
> 
> Last login: Tue Sep 13 14:32:56 2016 from 99.90.69.58
> Norman@bastion:~$ jumpbox user
>    
> 
> >> Installing rvm
>    RVM is already installed (rvm 1.27.0 (latest) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/])
> >> Checking for ruby v2.2.4
>    ruby is already installed (ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-linux])
> >> Checking for bosh v1.3184.1.0
>    bosh is already installed (BOSH 1.3184.1.0)
> >> **Installing cf**
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
>   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
> 100 6389k  100 6389k    0     0  3188k      0  0:00:02  0:00:02 --:--:-- 8993k
>    **installed CF CLI (cf version 6.21.1+6fd3c9f-2016-08-10)**
>    Git username is already set to 'Norman Abramovitz'
>    Git email address is already set to 'norm@starkandwayne.com'
>    git is configured
> 
> 
> 
>    ALL DONE

**Comment by jhunt** [comment]
Fixed.  cf cli only gets installed if it isn't already installed, or is a bad version.
