### ISSUE TITLE
Shoud useradd undo its work if it does not complete?

### ISSUE THREAD

**Issue by norman-abramovitz** [starkandwayne/jumpbox#18]
I ran the `jumpbox useradd` command and it prompted me for a public key.   I believe it was asking me for a public key which I thought was my personal public key.   It then prompted me for the bastion host account password.   That did not make sense since that account only had ssh keys.  I then killed script.

I then figured out where to get the bastion host keys from and ran the `jumpbox useradd` with the same input parameters.

I got the following response:
> Full name: Norman Abramovitz
> Username:  normdev
> useradd: user 'normdev' already exists

I am wondering if `jumpbox useradd` should undo it changes if the command fails execute completely or at least state to use `userdel` to clean things up.

**Comment by jhunt** [comment]
@givett modified the code to only create the user if it doesn't already exist, so it doesn't bail out.
