### ISSUE TITLE
Look at deprecating this script

### ISSUE THREAD

**Issue by jhunt** [starkandwayne/jumpbox#27]
Should we continue to maintain this script, since we have the [jumpbox-boshrelease](/cloudfoundry-community/jumpbox-boshrelease)?  I would be in favor of deprecating this repo and urging people to go use the BOSH release.

**Comment by jhunt** [comment]
@geofffranks / @dennisjbell thoughts?

**Comment by mkb** [comment]
There is plenty of call for jumpboxen not created by bosh, no?

**Comment by dennisjbell** [comment]
There may be need for this script for companies that already have bastion hosts that just need these extra utilities/apps/libs that can't use bosh-created bastion hosts. -- thinking of enterprise-level companies that have different organizations that provision/own them.

**Comment by jhunt** [comment]
@mkb: I don't personally think so; having a jumpbox with all the amenities, that BOSH keeps running is kind of nice.

@dennisjbell: in those circumstances, we've been unable to / prohibited from adding our own stuff to the jumpboxen, so the script is of limited usefulness in those scenarios.

**Comment by bodymindarts** [comment]
In codex this script is used to run on the terraform provisioned bastion. How is it possible to provision a jumpbox with BOSH when the BOSH needs to run behind a dmz and the only way to create it is from a jumpbox?

**Comment by jhunt** [comment]
It was just a thought, you guys.
