### ISSUE TITLE
Drop RVM in favor of system ruby

### ISSUE THREAD

**Issue by jhunt** [starkandwayne/jumpbox#34]
Two things have changed since we adopted RVM:

- Most CLIs are written in Go now, and packaged as standalone, static executables
- The distributions have caught up with modernity in the Ruby world (Ubu 18.04 LTS has ruby-2.5)

Change over to use the system package.

**Comment by ramonskie** [comment]
don't we need to wait for 18.04 stemcells first?

**Comment by jhunt** [comment]
This is the `jumpbox` script; we don't run it on stemcells.

**Comment by djvdorp** [comment]
Shouldn't this change have lead to a `v51` release? If anybody uses `master` now, their `genesis -v` will say `v50` from commit `9d67a98`, however current `v50` would be from commit `4806e88` (without having RVM and various other changes). I wanted to open a new issue for this, but maybe this is easier?

**Comment by jhunt** [comment]
I'm confused how genesis enters into the mix...

**Comment by djvdorp** [comment]
@jhunt sorry, did not have enough coffee, I meant `jumpbox -v` and have fixed my comment above now!

**Comment by jhunt** [comment]
Ah, okay then.  Yeah, we can version bump.  TBH, I just kind of forget about managing versions on this script because I have never had to "downgrade" and upgrades have always been mostly noops.
